# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

services:
  - mysql

env:
  - MYSQL_USER=root MYSQL_PASSWORD="" MYSQL_HOST=localhost MYSQL_DATABASE=idb

notifications:
  slack: cs373-idb:qbdxxyoOlhhavbkqCTQLOly5

install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r requirements.txt

before_script:
    - uname -a
    - printenv
    - pip list
    - mysql -e "create database IF NOT EXISTS idb;" -uroot

script:
    - date
    - ls -al
    - python3 database.py init_db
    - ls -al
    - python3 database.py load_pickled_data
    - ls -al
    - make models.html
    - ls -al
    - make IDB1.log
    - ls -al
    - make test
    - ls -al
    - make check
